@startuml

package "Process A" {
    component "Actor A" as actorA
    component "Actor B" as actorB
    component "Actor C" as actorC
}

package "Process B" {
    component "Actor D" as actorD
    component "Actor E" as actorE
}

interface "consul" as consul
note right
Manage cluster membership and
dispatch tasks to available cluster note
end note

cloud "Cluster" {
    package "Process C" {
        component "Grain A" as grainA
    }

    package "Process D" {
        component "Grain A" as grainAsub #ccc
    }
}

actorA <-> actorB : Local
actorC <-up-> actorB : Local
actorD <-down-> actorB : Remote

actorD <-> actorE : Local

actorE <-down-> consul : gRPC based call\nor plain remote call
consul <-down-> grainA
consul <.down.> grainAsub

@enduml